### PR TITLE
Add ability to load larger CLIP model. Fix CLI bug. 

### PR DESCRIPTION
**Pull request by afiaka87**

### CODE REVIEW

**Comment by afiaka87** [comment]
Note that I also removed the clip.py file in favor of installing a (pinned commit) of openAI's clip github repo.

**Comment by mroosen** [comment]
I've tried merging the pull request and tried your branch stand-alone, but getting the following error;

torch.nn.modules.module.ModuleAttributeError: 'DeepDaze' object has no attribute 'normalize_image'


`100%|███████████████████████████████████████| 256M/256M [00:17<00:00, 14.3MiB/s]^[[C
Imagining "an_ice_cream" from the depths of my weights...
Traceback (most recent call last):
  File "../run.py", line 43, in <module>
    doDefault("an ice cream", settingGroup[3])
  File "../run.py", line 6, in doDefault
    Imagine(
  File "/home/user/anaconda3/envs/deep-daze/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/media/user/lol/deep-daze/deep_daze/deep_daze.py", line 418, in forward
    self.model(self.clip_encoding, dry_run = True) # do one warmup step due to potential issue with CLIP and CUDA
  File "/home/user/anaconda3/envs/deep-daze/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/media/user/lol/deep-daze/deep_daze/deep_daze.py", line 159, in forward
    pieces.append(self.normalize_image(apper))
  File "/home/user/anaconda3/envs/deep-daze/lib/python3.8/site-packages/torch/nn/modules/module.py", line 778, in __getattr__
    raise ModuleAttributeError("'{}' object has no attribute '{}'".format(
torch.nn.modules.module.ModuleAttributeError: 'DeepDaze' object has no attribute 'normalize_image'
`

**Comment by afiaka87** [comment]
One second, I'm having lots of issues with being able to reliably install CLIP. I'm gonna change it back to the way you had it.

**Comment by afiaka87** [comment]
Thanks @mroosen, I'll patch that up.

**Pull request closed without merging**
